# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = QtWidgetsApplication1
DESTDIR = ./x64/Debug
CONFIG += debug
LIBS += -L"." \
    -l$(Qt_LIBS_)
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
HEADERS+=\
include/MyThread.h
include(QtWidgetsApplication1.pri)
win32:RC_FILE = QtWidgetsApplication1.rc
